site_name: pyracing
repo_url: https://github.com/esterni/pyracing
repo_name: GitHub

theme:
  name: 'material'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - List of Methods: functions.md
  - Data Points:
    - 'data-points\career_stats.md'
    - 'data-points\driver_stats.md'
    - 'data-points\event_results.md'
    - 'data-points\season_standings.md'
    - 'data-points\subsession_data.md'
    - 'data-points\active_op_count.md'
    - 'data-points\world_records.md'
    - 'data-points\current_seasons.md'

  - Modules: modules.md
  - Contributing: contributing.md

extra_css: 
  - css\custom.css