site_name: pyracing
repo_url: https://github.com/esterni/pyracing
repo_name: GitHub

theme:
  name: 'material'
  features:
    - toc:
      permalink: true

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Class Methods: functions.md
  - Returned Data: data.md
  - Modules: modules.md
  - Contributing: contributing.md
