site_name: pyracing
repo_url: https://github.com/esterni/pyracing
repo_name: GitHub

theme:
  name: 'material'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - Class Methods: functions.md
  - Data:
    - 'All-Data\career_stats.md'
    - 'All-Data\driver_stats.md'
    - 'All-Data\event_results.md'
    - 'All-Data\season_standings.md'
    - 'All-Data\subsession_data.md'
    - 'All-Data\active_op_count.md'
    - 'All-Data\world_records.md'
    - 'All-Data\current_seasons.md'

  - Modules: modules.md
  - Contributing: contributing.md

extra_css: 
  - css\custom.css