site_name: pyracing
repo_url: https://github.com/esterni/pyracing
repo_name: GitHub

theme:
  name: 'material'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - List of Methods: methods.md
  - Data Points: datapoints.md
  - Modules: modules.md
  - Contributing: contributing.md

extra_css: 
  - css\custom.css

google_analytics:
  - UA-173984844-1
  - auto