class EventResults(dict):
    pass



self.helm_color1 = dict['1']
self.winnerhelmcolor2 = dict['2']
self.finishing_position = dict['3']
self.winnerhelmcolor3 = dict['4']
self.winnerhelmcolor1 = dict['5']
self.bestquallaptime = dict['6']
self.subsession_bestlaptime = dict['7']
self.race_week_num = dict['8']
self.sessionid = dict['9']
self.finishedat = dict['10']
self.raw_start_time = dict['11']
self.starting_position = dict['12']
self.helm_color3 = dict['13']
self.helm_color2 = dict['14']
self.rowcount = dict['15']
self.clubpoints = dict['16']
self.dropracepoints = dict['17']
self.officialsession = dict['18']
self.groupname = dict['19']
self.seriesid = dict['20']
self.start_time = dict['21']
self.seasonid = dict['22']
self.custid = dict['23']
self.helm_licenselevel = dict['24']
self.winnerlicenselevel = dict['25']
self.rn = dict['26']
self.winnersgroupid = dict['27']
self.sesrank = dict['28']
self.carclassid = dict['29']
self.trackid = dict['30']
self.winnerdisplayname = dict['31']
self.carid = dict['32']
self.catid = dict['33']
self.season_quarter = dict['34']
self.licensegroup = dict['35']
self.winnerhelmpattern = dict['36']
self.evttype = dict['37']
self.bestlaptime = dict['38']
self.incidents = dict['39']
self.champpoints = dict['40']
self.subsessionid = dict['41']
self.season_year = dict['42']
self.champpointssort = dict['43']
self.start_date = dict['44']
self.strengthoffield = dict['45']
self.helm_pattern = dict['46']
self.clubpointssort = dict['47']
self.displayname = dict['48']


