

class SubSessionData:
    def __init__(self, dict):
        self.catid = dict['catid']
        self.cautiontype = dict['cautiontype']
        self.cornersperlap = dict['cornersperlap']
        self.driver_change_param1 = dict['driver_change_param1']
        self.driver_change_param2 = dict['driver_change_param2']
        self.driver_change_rule = dict['driver_change_rule']
        self.driver_changes = dict['driver_changes']
        self.eventavglap = dict['eventavglap']
        self.eventlapscomplete = dict['eventlapscomplete']
        self.eventstrengthoffield = dict['eventstrengthoffield']
        self.evttype = dict['evttype']
        self.league_season_id = dict['league_season_id']
        self.leagueid = dict['leagueid']
        self.leavemarbles = dict['leavemarbles']
        self.max_team_drivers = dict['max_team_drivers']
        self.maxweeks = dict['maxweeks']
        self.min_team_drivers = dict['min_team_drivers']
        self.ncautionlaps = dict['ncautionlaps']
        self.ncautions = dict['ncautions']
        self.nlapsforqualavg = dict['nlapsforqualavg']
        self.nlapsforsoloavg = dict['nlapsforsoloavg']
        self.nleadchanges = dict['nleadchanges']
        self.pointstype = dict['pointstype']
        self.privatesessionid = dict['privatesessionid']
        self.race_week_num = dict['race_week_num']
        self.rserv_status = dict['rserv_status']
        self.rubberlevel_practice = dict['rubberlevel_practice']
        self.rubberlevel_qualify = dict['rubberlevel_qualify']
        self.rubberlevel_race = dict['rubberlevel_race']
        self.rubberlevel_warmup = dict['rubberlevel_warmup']
        self.season_name = dict['season_name']
        self.season_quarter = dict['season_quarter']
        self.season_shortname = dict['season_shortname']
        self.season_year = dict['season_year']
        self.seasonid = dict['seasonid']
        self.series_name = dict['series_name']
        self.series_shortname = dict['series_shortname']
        self.seriesid = dict['seriesid']
        self.sessionid = dict['sessionid']
        self.sessionname = dict['sessionname']
        self.simsestype = dict['simsestype']
        self.simulatedstarttime = dict['simulatedstarttime']
        self.specialeventtype = dict['specialeventtype']
        self.specialeventtypetext = dict['specialeventtypetext']
        self.start_time = dict['start_time']
        self.subsessionid = dict['subsessionid']
        self.timeofday = dict['timeofday']
        self.track_config_name = dict['track_config_name']
        self.track_name = dict['track_name']
        self.trackid = dict['trackid']
        self.weather_fog_density = dict['weather_fog_density']
        self.weather_rh = dict['weather_rh']
        self.weather_skies = dict['weather_skies']
        self.weather_temp_units = dict['weather_temp_units']
        self.weather_temp_value = dict['weather_temp_value']
        self.weather_type = dict['weather_type']
        self.weather_var_initial = dict['weather_var_initial']
        self.weather_var_ongoing = dict['weather_var_ongoing']
        self.weather_wind_dir = dict['weather_wind_dir']
        self.weather_wind_speed_units = dict['weather_wind_speed_units']
        self.weather_wind_speed_value = dict['weather_wind_speed_value']

        self.driver = [self.Driver(x) for x in dict['rows']]

    class Driver:
        def __init__(self, dict):
            self.aggchamppoints = dict['aggchamppoints']
            self.avglap = dict['avglap']
            self.bestlapnum = dict['bestlapnum']
            self.bestlaptime = dict['bestlaptime']
            self.bestnlapsnum = dict['bestnlapsnum']
            self.bestnlapstime = dict['bestnlapstime']
            self.bestquallapat = dict['bestquallapat']
            self.bestquallapnum = dict['bestquallapnum']
            self.bestquallaptime = dict['bestquallaptime']
            self.car_color1 = dict['car_color1']
            self.car_color2 = dict['car_color2']
            self.car_color3 = dict['car_color3']
            self.car_number_color1 = dict['car_number_color1']
            self.car_number_color2 = dict['car_number_color2']
            self.car_number_color3 = dict['car_number_color3']
            self.car_pattern = dict['car_pattern']
            self.carclassid = dict['carclassid']
            self.carid = dict['carid']
            self.carnum = dict['carnum']
            self.carnumberfont = dict['carnumberfont']
            self.carnumberslant = dict['carnumberslant']
            self.carsponsor1 = dict['carsponsor1']
            self.carsponsor2 = dict['carsponsor2']
            self.ccName = dict['ccName']
            self.ccNameShort = dict['ccNameShort']
            self.champpoints = dict['champpoints']
            self.classinterval = dict['classinterval']
            self.clubid = dict['clubid']
            self.clubname = dict['clubname']
            self.clubpoints = dict['clubpoints']
            self.clubshortname = dict['clubshortname']
            self.custid = dict['custid']
            self.damage_model = dict['damage_model']
            self.displayname = dict['displayname']
            self.division = dict['division']
            self.divisionname = dict['divisionname']
            self.dropracepoints = dict['dropracepoints']
            self.evttypename = dict['evttypename']
            self.finishpos = dict['finishpos']
            self.finishposinclass = dict['finishposinclass']
            self.groupid = dict['groupid']
            self.heatinfoid = dict['heatinfoid']
            self.helm_color1 = dict['helm_color1']
            self.helm_color2 = dict['helm_color2']
            self.helm_color3 = dict['helm_color3']
            self.helm_pattern = dict['helm_pattern']
            self.hostid = dict['hostid']
            self.incidents = dict['incidents']
            self.interval = dict['interval']
            self.lapscomplete = dict['lapscomplete']
            self.lapslead = dict['lapslead']
            self.league_points = dict['league_points']
            self.license_change_oval = dict['license_change_oval']
            self.license_change_road = dict['license_change_road']
            self.licensecategory = dict['licensecategory']
            self.licensegroup = dict['licensegroup']
            self.max_pct_fuel_fill = dict['max_pct_fuel_fill']
            self.multiplier = dict['multiplier']
            self.newcpi = dict['newcpi']
            self.newirating = dict['newirating']
            self.newlicenselevel = dict['newlicenselevel']
            self.newsublevel = dict['newsublevel']
            self.newttrating = dict['newttrating']
            self.officialsession = dict['officialsession']
            self.oldcpi = dict['oldcpi']
            self.oldirating = dict['oldirating']
            self.oldlicenselevel = dict['oldlicenselevel']
            self.oldsublevel = dict['oldsublevel']
            self.oldttrating = dict['oldttrating']
            self.optlapscomplete = dict['optlapscomplete']
            self.pos = dict['pos']
            self.quallaptime = dict['quallaptime']
            self.reasonout = dict['reasonout']
            self.reasonoutid = dict['reasonoutid']
            self.restrictresults = dict['restrictresults']
            self.sessionstarttime = dict['sessionstarttime']
            self.simsesname = dict['simsesname']
            self.simsesnum = dict['simsesnum']
            self.simsestypename = dict['simsestypename']
            self.startpos = dict['startpos']
            self.suit_color1 = dict['suit_color1']
            self.suit_color2 = dict['suit_color2']
            self.suit_color3 = dict['suit_color3']
            self.suit_pattern = dict['suit_pattern']
            self.track_category = dict['track_category']
            self.track_catid = dict['track_catid']
            self.vehiclekeyid = dict['vehiclekeyid']
            self.weight_penalty_kg = dict['weight_penalty_kg']
            self.wheel_chrome = dict['wheel_chrome']
            self.wheel_color = dict['wheel_color']


# Race laps for all drivers of a session
class RaceLapsAll:
    def __init__(self, dict):
        self.details = self.Details(dict['details'])
        self.driver = [self.Driver(x) for x in dict['startgrid']]
        self.lapdata = [self.LapData(x) for x in dict['lapdata']]

    class Details:
        def __init__(self, dict):
            self.driverChanges = dict['driverChanges']
            self.eventDate = dict['eventDate']
            self.eventDateUTCMilliSecs = dict['eventDateUTCMilliSecs']
            self.eventType = dict['eventType']
            self.eventTypeName = dict['eventTypeName']
            self.nLapsForQualAvg = dict['nLapsForQualAvg']
            self.nLapsForSoloAvg = dict['nLapsForSoloAvg']
            self.officialSession = dict['officialSession']
            self.privateSessionID = dict['privateSessionID']
            self.privateSessionName = dict['privateSessionName']
            self.race_panel_img = dict['race_panel_img']
            self.raceWeek = dict['raceWeek']
            self.seasonID = dict['seasonID']
            self.seasonName = dict['seasonName']
            self.seasonShortName = dict['seasonShortName']
            self.seriesName = dict['seriesName']
            self.seriesShortName = dict['seriesShortName']
            self.sessionId = dict['sessionId']
            self.subSessionId = dict['subSessionId']
            self.trackConfig = dict['trackConfig']
            self.trackid = dict['trackid']
            self.trackName = dict['trackName']

    class Driver:
        def __init__(self, dict):
            self.avgLapTime = dict['avgLapTime']
            self.carnum = dict['carnum']
            self.custid = dict['custid']
            self.displayName = dict['displayName']
            self.fastestLapNum = dict['fastestLapNum']
            self.fastestLapTime = dict['fastestLapTime']
            self.finishPos = dict['finishPos']
            self.friend = dict['friend']
            self.groupid = dict['groupid']
            self.helmetColor1 = dict['helmetColor1']
            self.helmetColor2 = dict['helmetColor2']
            self.helmetColor3 = dict['helmetColor3']
            self.helmetPattern = dict['helmetPattern']
            self.licenseColor = dict['licenseColor']
            self.numIncidents = dict['numIncidents']
            self.points = dict['points']
            self.startPos = dict['startPos']
            self.watch = dict['watch']

    class LapData:
        def __init__(self, dict):
            self.carnum = dict['carnum']
            self.custid = dict['custid']
            self.flags = dict['flags']
            self.lapnum = dict['lapnum']
            self.sesTime = dict['sesTime']


# Race laps for single driver of a session
class RaceLapsDriver:
    def __init__(self, dict):
        self.driver = self.Driver(dict['drivers'])
        self.header = self.Header(dict['header'])
        self.lapData = [self.LapData(x) for x in dict['lapData']]

    class LapData:
        def __init__(self, dict):
            self.custid = dict['custid']
            self.flags = dict['flags']
            self.lap_num = dict['lap_num']
            self.ses_time = dict['ses_time']

    class Header:
        def __init__(self, dict):
            self.carColor1 = dict['carColor1']
            self.carColor2 = dict['carColor2']
            self.carColor3 = dict['carColor3']
            self.carid = dict['carid']
            self.carNum = dict['carNum']
            self.carPattern = dict['carPattern']
            self.eventDate = dict['eventDate']
            self.eventDateUTCMilliSecs = dict['eventDateUTCMilliSecs']
            self.eventtype = dict['eventtype']
            self.eventTypeName = dict['eventTypeName']
            self.nlapsforqual = dict['nlapsforqual']
            self.nlapsforsolo = dict['nlapsforsolo']
            self.seasonName = dict['seasonName']
            self.seasonShortName = dict['seasonShortName']
            self.seriesName = dict['seriesName']
            self.seriesShortName = dict['seriesShortName']
            self.sessionId = dict['sessionId']
            self.subSessionId = dict['subSessionId']
            self.suitColor1 = dict['suitColor1']
            self.suitColor2 = dict['suitColor2']
            self.suitColor3 = dict['suitColor3']
            self.suitPattern = dict['suitPattern']
            self.teamName = dict['teamName']
            self.trackConfig = dict['trackConfig']
            self.trackID = dict['trackID']
            self.trackName = dict['trackName']

    class Driver:
        def __init__(self, dict):
            self.bestlapnum = dict['bestlapnum']
            self.bestlaptime = dict['bestlaptime']
            self.bestnlapsnum = dict['bestnlapsnum']
            self.bestnlapstime = dict['bestnlapstime']
            self.bestquallapat = dict['bestquallapat']
            self.bestquallapnum = dict['bestquallapnum']
            self.bestquallaptime = dict['bestquallaptime']
            self.custid = dict['custid']
            self.displayname = dict['displayname']
            self.helm_color1 = dict['helm_color1']
            self.helm_color2 = dict['helm_color2']
            self.helm_color3 = dict['helm_color3']
            self.helm_pattern = dict['helm_pattern']
            self.licenselevel = dict['licenselevel']
