name: Integration Test

on:
  push:
    branches: master
  schedule:
    # 4 AM Central Daylight Time
    - cron: '0 9 * * *'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.0
          architecture: x64
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Integration Tests
        env:
          IRACING_USERNAME: ${{ secrets.IRACING_USERNAME }}
          IRACING_PASSWORD: ${{ secrets.IRACING_PASSWORD }}
        run: |
          python -m unittest discover integration_tests/ -p "*_test.py"